version: "3.9"

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      MONGODB_URI= mongodb://adsajanstudy_db_user:5GOsgoGSf0zdIyLI@ac-knh5myf-shard-00-00.fdtgmgf.mongodb.net:27017,ac-knh5myf-shard-00-01.fdtgmgf.mongodb.net:27017,ac-knh5myf-shard-00-02.fdtgmgf.mongodb.net:27017/?ssl=true&replicaSet=atlas-safunw-shard-0&authSource=admin&appName=Cluster0
      MONGODB_DB=adsajanstudy_db_user
      depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

volumes:
  mongo-data:



